//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void IDAC0_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define BTN_CLOSE_PIN               (2)
#define BTN_CLOSE_PORT              (gpioPortF)

#define BTN_OPEN_PIN                (0)
#define BTN_OPEN_PORT               (gpioPortA)

#define GPIO_EM4WU0_PIN             (0)
#define GPIO_EM4WU0_PORT            (gpioPortA)

#define GPIO_EM4WU4_PIN             (2)
#define GPIO_EM4WU4_PORT            (gpioPortF)

#define LED_GREEN_PIN               (14)
#define LED_GREEN_PORT              (gpioPortC)

#define LED_RED_PIN                 (15)
#define LED_RED_PORT                (gpioPortC)

#define NC_13_PIN                   (6)
#define NC_13_PORT                  (gpioPortD)

#define NC_14_PIN                   (7)
#define NC_14_PORT                  (gpioPortD)

#define NC_23_PIN                   (12)
#define NC_23_PORT                  (gpioPortE)

#define NC_24_PIN                   (13)
#define NC_24_PORT                  (gpioPortE)

#define NC_6_PIN                    (8)
#define NC_6_PORT                   (gpioPortB)

#define NRF_CE_PIN                  (14)
#define NRF_CE_PORT                 (gpioPortB)

#define NRF_IRQ_PIN                 (13)
#define NRF_IRQ_PORT                (gpioPortB)

#define NRF_SPI_CLK_PIN             (7)
#define NRF_SPI_CLK_PORT            (gpioPortB)

#define NRF_SPI_MISO_PIN            (1)
#define NRF_SPI_MISO_PORT           (gpioPortC)

#define NRF_SPI_MOSI_PIN            (0)
#define NRF_SPI_MOSI_PORT           (gpioPortC)

#define NRF_SPI_SOFT_CSN_PIN        (11)
#define NRF_SPI_SOFT_CSN_PORT       (gpioPortB)

// [User-defined pin name abstraction]$

#endif

